version: '3.7'

services:

  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/react-app'
      - '/react-app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${PORT}:${PORT}
